# Generated by Django 6.0.3 on 2026-08-12 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('cause_slug', models.SlugField(max_length=80)),
                ('cause_title', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('donation_type', models.CharField(choices=[('one-time', 'One-time'), ('monthly', 'Monthly')], default='one-time', max_length=20)),
                ('send_updates', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=80)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='core.donationcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
